export const GET_PAGES_REQUEST = 'GET_PAGES_REQUEST';
export const GET_PAGES_SUCCESS = 'GET_PAGES_SUCCESS';
export const GET_PAGES_FAIL = 'GET_PAGES_FAIL';

export const GET_SINGLE_PAGES_REQUEST = 'GET_SINGLE_PAGES_REQUEST';
export const GET_SINGLE_PAGES_SUCCESS = 'GET_SINGLE_PAGES_SUCCESS';
export const GET_SINGLE_PAGES_FAIL = 'GET_SINGLE_PAGES_FAIL';

export const THEME_TOGGLE = 'THEME_TOGGLE';
export const LANGUAGE_TOGGLE = 'LANGUAGE_TOGGLE';
